### ISSUE TITLE
ancestral_paths_v3.bcf

### ISSUE THREAD

**Issue by DongliangXu** [ekirving/ms_paper#1]
Hi：
I am a researcher currently working on a project that involves the analysis of genetic ancestry data. As part of this work, I am actively testing various methodologies and tools to ensure the accuracy and robustness of our findings.

Recently, I encountered your esteemed work, which has been highly recommended by my colleagues for its thoroughness and the valuable insights it provides into the field of genetic ancestry. I am particularly interested in the 'ancestral_paths_v3.bcf' file, which I understand is a critical component of your research.

Regrettably, I have found that this file is missing from the resources available to me. The absence of this file is hindering my ability to fully test and integrate the procedures as outlined in your study. I believe that access to this file would greatly benefit my research and potentially allow me to contribute more effectively to the scientific community's understanding of genetic ancestry.

I am reaching out with the hope that you might be able to share the 'ancestral_paths_v3.bcf' file with me. Your cooperation would be invaluable, and I would like to assure you that the file will be used solely for the purposes of research and in full compliance with any applicable data usage agreements.

Please let me know if there are any conditions or requirements for sharing this file, or if there are alternative sources you could direct me to. I am also open to discussing any concerns you may have regarding the use of this data.

Thank you very much for your time and consideration.

**Comment by ekirving** [comment]
Hello, you can download the imputed dataset with the ancestral path annotations here:
https://erda.ku.dk/archives/917f1ac64148c3800ab7baa29402d088/published-archive.html

To make the `ancestral_paths_v3.bcf` file, all you need to do is concatenate these VCFs together and convert to BCF.

**Comment by DongliangXu** [comment]
Thank you very much for your response. I have successfully downloaded and organized the VCF files, but I've noticed that the Snakemake pipeline requires the VCF files to include an 'AA' tag, which I believe refers to the ancestral allele.
### vcf
>1       
754503  
1_754503_G_A    
G       
A       
100     
PASS    
pan_troglodytes=N;MASK_1000G;RAF=0.663938;AF=0.783465;INFO=0.794;AN=4966;AC=3964        
GT:DS:GP:HS:AP  
1|0:1:0,1,0:631658902:2|2


###  snakemake

> rule list_callable_sites:
    """
    Make a list of all the callable sites in the current dataset
    """
    input:
        vcf=lambda wildcards: config["samples"][wildcards.dataset]["genotypes"],
    output:
        tsv="data/sites/{dataset}_sites.tsv.gz",
    shell:
        r"bcftools query --print-header --format '%CHROM\t%POS\t%ID\t%REF\t%ALT\t%INFO/AA\n' {input.vcf} | "
        r"sed 's/|||//' | tr [acgt] [ACGT] | bgzip -c > {output.tsv}"`




###  shell
`bcftools query -f '%CHROM\t%POS\t%ID\t%REF\t%ALT\t%INFO/AA\n' ancestral_paths_v3.bcf`
`[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)`
`Error: no such tag defined in the VCF header: INFO/AA`


Can I directly use the reference allele as the ancestral allele? Is this the correct approach?

**Comment by ekirving** [comment]
You can annotate your VCF with the `AA` tag using a Thousand Genomes Project VCF.

**Comment by DongliangXu** [comment]
okay, thank you very much
